### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by vikesh-raj** [brawer/wikidata-qrank#11]
I want to know the update frequency of the `qrank.csv.gz` file. It is mentioned in the [website](https://qrank.wmcloud.org/) that it is updated periodically but no information related to the periodicity.

Also, Is there a possibility to download older files ?

**Comment by brawer** [comment]
There's a cron job that checks once every day whether a fresh Wikidata dump is available; if so, QRank gets recomputed. Currently, Wikidata dumps are generated about once per week; accordingly, QRank gets updated about weekly.

Sorry, there's currently no archive of old QRank files.
