### ISSUE TITLE
Page down

### ISSUE THREAD

**Issue by wipfli** [brawer/wikidata-qrank#13]
https://qrank.wmcloud.org/ seems to be down:

![image](https://user-images.githubusercontent.com/53421382/219907913-4f66fabe-4376-45f6-b768-d6271f6a9b49.png)

**Comment by wipfli** [comment]
I still had an qrank.csv file on my machine from November 2022.

If anyone wants to download it you can get it here:

https://pub-726b01260c98468a9387cc0dfcb7386b.r2.dev/qrank-2022-11-23.csv

**Comment by brawer** [comment]
Thanks for the report, fixed.

Also, I’ve set up [free uptime monitoring](https://brawer.freshping.io/reports?check_id=968186) so I should get alerted in the future when the server goes down. Hopefully, their alert emails won’t get filtered out by my spam filter.
