### ISSUE TITLE
Index, WA and Hanna, AB have very high qrank scores

### ISSUE THREAD

**Issue by cldellow** [brawer/wikidata-qrank#20]
I was trying to use QRank to prioritize cities on a map. I noticed some oddities:

- [Q747623](https://www.wikidata.org/wiki/Q747623) has a high score: 61,113
- [Q1507629](https://www.wikidata.org/wiki/Q1507629) has an even higher score: 3,421,327

These are two small towns: Hanna, Alberta (population 2,559) and Index, Washington (population 155).

I wonder if there is a conflation error that is inflating their scores? For example, https://en.wikipedia.org/wiki/Hannah is a disambiguation page that includes Hanna, AB. https://en.wikipedia.org/wiki/Index is a disambiguation page that includes Index, WA.

It seems somewhat prevalent, in Washington state alone, the towns of Cheney, Pullman and Aberdeen also have suspiciously high scores (and each shares a name with much more famous entities that have Wikipedia disambiguation pages).

I'm not familiar enough with how pageviews are counted in the Wikipedia project, but do you know if that might be the case, or if it'd be a straight forward fix?

**Comment by athalhammer** [comment]
I wouldn't say something is off - there was just some type of peak last January for Index, Washington (will figure out what it was afterwards)

https://pageviews.wmcloud.org/?project=en.wikipedia.org&platform=all-access&agent=user&redirects=0&start=2023-01-01&end=2023-02-01&pages=Index,_Washington

A similar thing happened to Hannah, Alberta in October.

I'm not sure if Q-rank tries to flatten out these peaks or just factors them in as total count. After all, something that is extremely popular on a single day may actually deserve some general salience.

**Comment by cldellow** [comment]
Oh, I feel silly for assuming it was zebras, when it's actually just horses. Thank you for those pointers to the pageviews.

The data for Hanna seems plausible. I guess that's just the score it deserves, and I ought to blend it with some other factors to get the effect I want.

The Index, Washington data seems like it might be non-human traffic. The [`Mobile web` view](https://pageviews.wmcloud.org/?project=en.wikipedia.org&platform=mobile-web&agent=user&redirects=0&start=2023-01-01&end=2023-02-01&pages=Index,_Washington) has a suspicious gap on Sunday the 15th:

![Selection_643](https://github.com/brawer/wikidata-qrank/assets/193185/e4622d64-8d2f-48a6-bb87-04e8eea7e85b)

Seems weird that it has a baseline of ~40/day, spikes to hundreds of thousands, goes back to ~40/day, then spikes back again. Maybe it was a newsworthy event followed only by very devout folks who don't browse the web on Sundays? :)

> I'm not sure if Q-rank tries to flatten out these peaks or just factors them in as total count. After all, something that is extremely popular on a single day may actually deserve some general salience.

Yes, this is a good point. According to the [design doc](https://github.com/brawer/wikidata-qrank/blob/main/doc/design.md), I think it sums the pageviews of the trailing 12 months.

There seem to me to be two legitimate scenarios where spiky traffic happens:

1. Newsworthy events. See if you can spot Carrie Fisher's death:

![Selection_645](https://github.com/brawer/wikidata-qrank/assets/193185/dca99473-1e88-4473-8c49-fa980f929c09)

2. Anniversaries or periodic events.

Anniversaries: 9/11 has reliable spikes every 365 days on its anniversary:

![Selection_645](https://github.com/brawer/wikidata-qrank/assets/193185/8699e97f-0437-498c-83ce-8df428c00cd1)

Movable feasts like Easter have spikes that occur on different days, depending on which day the holiday falls that year:

![Selection_646](https://github.com/brawer/wikidata-qrank/assets/193185/3eaae1c7-a830-4445-9338-dab57a3a8d00)

I guess there are multiple ways to decide which value to take. The trailing 12 months is neat in that it captures newsworthy events, but I guess it also means that a data error (which is what I believe the Index, WA case to be) will take 12 months to wash out.

It would be cool if other measures could be exported--for example, the median of the max annual value for the last N years. That would likely be a more suitable measure for my case, whereas I can imagine the current measure would be more suitable for someone ranking pop culture / news events.

Definitely very use case specific, though; I'm not sure how to balance the different concerns.

**Comment by athalhammer** [comment]
There must have been some type of media mention of Index, Washington around that time...  Possibly something on television. The edits are more active on these days as well:

![image](https://github.com/brawer/wikidata-qrank/assets/832500/67db39cc-a0c4-4360-b783-0f37786fe863)

**Comment by brawer** [comment]
> The Index, Washington data seems like it might be non-human traffic

The Wikimedia analytics team tries to separate queries from (human) users vs. automated traffic, and qrank is only processing the `pageviews-*-user.bz2` files in the [Wikimedia log dumps](https://dumps.wikimedia.org/other/pageview_complete/2024/2024-03/).

**Comment by brawer** [comment]
OK to close this issue, or does it need follow-up?

**Comment by cldellow** [comment]
Yup, sorry for leaving it dangling!
