### ISSUE TITLE
qrank.csv.gz missing

### ISSUE THREAD

**Issue by bdon** [brawer/wikidata-qrank#22]
The download link to https://qrank.wmcloud.org/download/qrank.csv.gz seems to 404 today, is this a temporary blip or has it moved?

Thanks!

**Comment by brawer** [comment]
Oh no! I'm currently traveling in Taiwan, but will soon be back home in Switzerland and then I'll have a look. Sorry about this disruption.

**Comment by sdrll** [comment]
hi, do you have any news about this issue ?

**Comment by brawer** [comment]
Fixed. Sorry for the long delay, it would be good to have more people on this project so I can go traveling.
