### ISSUE TITLE
Allow Range headers for CORS

### ISSUE THREAD

**Issue by underwhelmingToaster** [brawer/wikidata-qrank#7]
The following error occurs when trying to read a range from "https://qrank.wmcloud.org/download/osmviews.tiff":

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://qrank.wmcloud.org/download/osmviews.tiff. (Reason: header ‘range’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).`

This is solved by allowing the range header:
`Header set Access-Control-Allow-Headers "Range"`

**Comment by brawer** [comment]
Done.

```
$ curl -I -X OPTIONS https://qrank.wmcloud.org/download/osmviews.tiff
HTTP/2 204 
server: nginx/1.18.0
date: Mon, 21 Mar 2022 08:15:30 GMT
access-control-allow-headers: ETag, If-Match, If-None-Match, If-Modified-Since, If-Range, Range
access-control-allow-methods: GET, OPTIONS
access-control-allow-origin: *
access-control-expose-headers: ETag
access-control-max-age: 86400
allow: GET, OPTIONS
[...]
```
