### ISSUE TITLE
qrank.wmcloud.org returns 502

### ISSUE THREAD

**Issue by SahAssar** [brawer/wikidata-qrank#8]
Hello and thanks for this dataset!

The qrank.wmcloud.org server returns HTTP 502 for me, is that possible to fix?

**Comment by brawer** [comment]
Oops, thanks for letting me know! I'm currently on a long bicycle tour, but of course I'll fix the server when I'm back home end of September. I do realize that this is a rather long downtime, and I am sorry about that. If you or someone else wants to co-maintain the service, please do not hesitate to tell.

**Comment by jimblackler** [comment]
Is there an alternative place I can download qrank.csv.gz in the meantime? It would be perfect for a project of mine.

**Comment by jimblackler** [comment]
Thank you so much.

**Comment by brawer** [comment]
This is now fixed, sorry about the outage! In the future, it would be good if we had multiple admins who can restart the server if needed. Then, I can go on vacation again :-) Maintenance should be needed quite rarely; this was actually the first time. Please contact me by email at sascha@brawer.ch if you’re interested.
